# ===- act/back_end/moe/__init__.py - MoE Verification -----------------====#

from act.back_end.moe.factory import (
    OutputMoEFactoryConfig,
    build_act_moe_program,
    build_act_router_program,
    build_output_moe,
    load_output_moe_checkpoint,
)
from act.back_end.moe.model import OutputLevelMoE, RoutingDecision
from act.back_end.moe.hz_routing import (
    CandidateReport,
    RouteBranch,
    TopKSetBranch,
    TopKSetDomain,
    TopKSetReport,
    TopKMembershipDomain,
    analyze_candidates,
    analyze_topk_sets,
    condition_topk_membership,
    condition_topk_set,
    guarded_input_domain,
    guarded_input_topk_set,
)
from act.back_end.moe.schema import (
    GateKind,
    OutputLevelMoEProgram,
    OutputLevelMoESpec,
    TiePolicy,
)
from act.back_end.moe.route_a import (
    RouteAEngine,
    RouteAVerificationReport,
    RouterAnalysis,
)
from act.back_end.moe.verifier import verify_output_gate_elimination
from act.back_end.moe.weighted_top2 import (
    SAFE_WEIGHTED_RANGE,
    SAFE_WEIGHTED_SEGMENTED,
    SharedInputPairHZ,
    UNKNOWN_WEIGHTED_NUMERICAL,
    UNKNOWN_WEIGHTED_RELAXATION,
    UNKNOWN_WEIGHTED_SOLVER_LIMIT,
    UNSAFE_FULL_FORWARD_FALLBACK,
    WeightedTop2F0Decision,
    WeightedTop2F0Encoding,
    build_weighted_top2_f0,
    linear_safety_rows,
    mccormick_contains,
    mccormick_inequalities,
    shared_input_pair_hz,
    solve_weighted_top2_f0,
)

__all__ = [
    "GateKind",
    "CandidateReport",
    "OutputLevelMoE",
    "OutputLevelMoEProgram",
    "OutputLevelMoESpec",
    "OutputMoEFactoryConfig",
    "RoutingDecision",
    "RouteBranch",
    "TopKSetBranch",
    "TopKSetDomain",
    "TopKSetReport",
    "RouteAEngine",
    "RouteAVerificationReport",
    "RouterAnalysis",
    "TiePolicy",
    "TopKMembershipDomain",
    "SharedInputPairHZ",
    "SAFE_WEIGHTED_RANGE",
    "SAFE_WEIGHTED_SEGMENTED",
    "UNKNOWN_WEIGHTED_NUMERICAL",
    "UNKNOWN_WEIGHTED_RELAXATION",
    "UNKNOWN_WEIGHTED_SOLVER_LIMIT",
    "UNSAFE_FULL_FORWARD_FALLBACK",
    "WeightedTop2F0Decision",
    "WeightedTop2F0Encoding",
    "analyze_candidates",
    "analyze_topk_sets",
    "build_act_moe_program",
    "build_act_router_program",
    "build_output_moe",
    "build_weighted_top2_f0",
    "condition_topk_membership",
    "condition_topk_set",
    "guarded_input_domain",
    "guarded_input_topk_set",
    "linear_safety_rows",
    "load_output_moe_checkpoint",
    "mccormick_contains",
    "mccormick_inequalities",
    "shared_input_pair_hz",
    "solve_weighted_top2_f0",
    "verify_output_gate_elimination",
]
