"""Render review-paper tables from unchanged archived reviews (stdlib only).

No model, solver, raw tensor, or embedded server path is accessed. Positive
counts retain their original evidence grade; reconstruction is not reproof.
"""
import argparse
import hashlib
import importlib.util
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = 'paper/results/submission_tables.tex'
METAMOE_ARCHIVE = 'docs/metamoe_las_followup_archive_20260923_r1.json'
METAMOE_CONFIG = 'af662082da17e953960ba1127d0f0fcf8783f0dd5810ce9b0bd8f43ab6aa031c'


def metamoe_accounting(archive):
    """Recount saved terminals, not re-prove model bounds or rerun solvers."""
    if (archive['audit'] != 'PASS' or archive['issues'] != 0 or
            archive['config_sha256'] != METAMOE_CONFIG or
            archive['numerical_guarantees_equated'] is not False):
        raise ValueError('MetaMoE archive identity/contract')
    expected = {'cifar10_' + str(i) for i in (1, 2, 4, 5, 7)} | {
        'mnist_' + str(i) for i in (1, 3, 7, 9, 10)}
    contracts = {
        'act': ('POSITIVE', 'HZ_POLICY_ACCEPTED'),
        'author': ('BACKEND_POSITIVE', 'AUTHOR_BACKEND_NUMERICAL_SUFFICIENT_FILTER'),
    }
    rows = archive['rows']
    if len(rows) != 20 or any(r['arm'] not in contracts for r in rows):
        raise ValueError('MetaMoE denominator/arm')
    output, positives = [], {}
    for arm, (positive, grade) in contracts.items():
        selected = [r for r in rows if r['arm'] == arm]
        if len(selected) != 10 or {r['id'] for r in selected} != expected:
            raise ValueError('MetaMoE missing/duplicate request')
        counts = {state: 0 for state in (positive, 'UNKNOWN', 'TIMEOUT')}
        for r in selected:
            if r['status'] not in counts:
                raise ValueError('unhandled MetaMoE terminal: do not silently discard')
            if r['grade'] != (grade if r['status'] == positive else 'NONE'):
                raise ValueError('MetaMoE evidence grade')
            if (type(r['seconds']) not in (int, float) or
                    not math.isfinite(r['seconds']) or r['seconds'] < 0):
                raise ValueError('MetaMoE missing/invalid charged cost')
            counts[r['status']] += 1
        positives[arm] = {r['id'] for r in selected if r['status'] == positive}
        output.append(dict(arm=arm, n=10, positive=counts[positive], unsafe=0,
                           unknown=counts['UNKNOWN'], timeout=counts['TIMEOUT'], error=0,
                           mean_seconds=math.fsum(r['seconds'] for r in selected) / 10))
    for key, value in (
            ('positive_intersection', positives['act'] & positives['author']),
            ('act_only_positive', positives['act'] - positives['author']),
            ('author_only_positive', positives['author'] - positives['act'])):
        if archive[key] != sorted(value):
            raise ValueError('MetaMoE paired-set accounting')
    return output


def accounting(root):
    spec = importlib.util.spec_from_file_location('archived_tables', root / 'scripts/rebuild_moe_main_tables.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def render(root=ROOT):
    base = accounting(root)
    raw = {key: (root / path).read_bytes() for key, path in base.SOURCES.items()}
    rows = base.build({key: json.loads(data) for key, data in raw.items()})
    old = base.render(rows, {key: hashlib.sha256(data).hexdigest() for key, data in raw.items()})
    if old != (root / 'paper/results/main_tables.md').read_text():
        raise ValueError('historical main table differs from archived accounting')
    lines = ['% Generated by render_submission_tables.py; accounting, not reproof.',
             r'\begin{table}[ht]', r'\centering\small',
             r'\caption{Historical new-input confirmation: empirical policy acceptances, not source-complete strict certificates. All 23 primary gains have audited input-containment gaps. Each cell is policy SAFE / solved, out of 100; solved includes replayed UNSAFE. All arms have the same 300-second cap.}',
             r'\label{tab:confirmation}', r'\begin{tabular}{lrrr}', r'\toprule',
             r'Model & Adaptive & Matched & Legacy \\', r'\midrule']
    for model in ('seed0', 'seed1', 'seed2'):
        cells = []
        for arm in ('adaptive', 'matched', 'legacy'):
            row, = [r for r in rows if r['cohort'] == 'MLP confirmation' and r['model'] == model and r['arm'] == arm]
            cells.append(f"{row['positive']} / {row['positive'] + row['unsafe']}")
        lines.append(model.replace('seed', 'Seed ') + ' & ' + ' & '.join(cells) + r' \\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}', '',
              r'\begin{table}[ht]', r'\centering\small',
              r'\caption{External-path and cross-family results. P is a HZ-policy acceptance (HZ) or CROWN numerical filter (CF), not a common strict-certificate grade. U is replayed UNSAFE; ? is UNKNOWN; T is TIMEOUT. Costs include unsuccessful requests.}',
              r'\label{tab:external}', r'\begin{tabular}{llrrrrrr}', r'\toprule',
              r'Cohort / method & Grade & N & P & U & ? & T & Mean s \\', r'\midrule']
    for cohort, title, arms in (
            ('MLP external', 'MLP', (('adaptive', 'ACT', 'HZ'), ('crown', 'CROWN path', 'CF'))),
            ('Conv V2', 'Conv', (('adaptive', 'Adaptive', 'HZ'), ('monolithic', 'Matched', 'HZ'), ('crown', 'CROWN path', 'CF')))):
        for arm, name, grade in arms:
            subset = [r for r in rows if r['cohort'] == cohort and r['arm'] == arm]
            n = sum(r['n'] for r in subset)
            counts = [sum(r[k] for r in subset) for k in ('positive', 'unsafe', 'unknown', 'timeout')]
            seconds = sum(r['mean_seconds'] * r['n'] for r in subset) / n
            cells = [title + ' / ' + name, grade, str(n), *(str(c) for c in counts), f'{seconds:.2f}']
            lines.append(' & '.join(cells) + r' \\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}', '']
    lines += [r'\begin{table}[ht]', r'\centering\small',
              r'\caption{Separate repaired MetaMoE follow-up: ten observed inputs per arm, 300 seconds per request. HZ is policy acceptance; AF is an author numerical sufficient filter, not the same strict-proof grade. The author arm includes the disclosed compatibility wrapper and route-invariance adapter. No ACT-only positive occurs.}',
              r'\label{tab:metamoe}', r'\begin{tabular}{llrrrrrrr}', r'\toprule',
              r'Method & Grade & N & P & U & ? & T & Error & Mean s \\', r'\midrule']
    for row in metamoe_accounting(json.loads((root / METAMOE_ARCHIVE).read_bytes())):
        name, grade = ('ACT', 'HZ') if row['arm'] == 'act' else ('Repaired author', 'AF')
        cells = [name, grade, *(str(row[k]) for k in
                 ('n', 'positive', 'unsafe', 'unknown', 'timeout', 'error')),
                 f"{row['mean_seconds']:.2f}"]
        lines.append(' & '.join(cells) + r' \\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--write', action='store_true', help='create a NEW rendering; refuse overwrite')
    args = parser.parse_args()
    content = render()
    if args.check:
        if (ROOT / OUTPUT).read_text() != content:
            raise ValueError('review-paper table drift')
        print('PASS: review-paper tables reproduce the archived accounting')
    elif args.write:
        with (ROOT / OUTPUT).open('x') as stream:
            stream.write(content)
    else:
        print(content, end='')


if __name__ == '__main__':
    main()
