"""Render review-paper tables from unchanged archived reviews (stdlib only).

No model, solver, raw tensor, or embedded server path is accessed. Positive
counts retain their original evidence grade; reconstruction is not reproof.
"""
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = 'paper/results/submission_tables.tex'


def accounting(root):
    spec = importlib.util.spec_from_file_location('archived_tables', root / 'scripts/rebuild_moe_main_tables.py')
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def render(root=ROOT):
    base = accounting(root)
    raw = {key: (root / path).read_bytes() for key, path in base.SOURCES.items()}
    rows = base.build({key: json.loads(data) for key, data in raw.items()})
    old = base.render(rows, {key: hashlib.sha256(data).hexdigest() for key, data in raw.items()})
    if old != (root / 'paper/results/main_tables.md').read_text():
        raise ValueError('historical main table differs from archived accounting')
    lines = ['% Generated by render_submission_tables.py; accounting, not reproof.',
             r'\begin{table}[ht]', r'\centering\small',
             r'\caption{New-input confirmation. Each cell is policy-accepted SAFE / solved, out of 100. Solved includes replayed UNSAFE. All arms have the same 300-second request cap.}',
             r'\label{tab:confirmation}', r'\begin{tabular}{lrrr}', r'\toprule',
             r'Model & Adaptive & Matched & Legacy \\', r'\midrule']
    for model in ('seed0', 'seed1', 'seed2'):
        cells = []
        for arm in ('adaptive', 'matched', 'legacy'):
            row, = [r for r in rows if r['cohort'] == 'MLP confirmation' and r['model'] == model and r['arm'] == arm]
            cells.append(f"{row['positive']} / {row['positive'] + row['unsafe']}")
        lines.append(model.replace('seed', 'Seed ') + ' & ' + ' & '.join(cells) + r' \\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}', '',
              r'\begin{table}[ht]', r'\centering\small',
              r'\caption{External-path and cross-family results. P is a HZ-policy acceptance (HZ) or CROWN numerical filter (CF), not a common strict-certificate grade. U is replayed UNSAFE; ? is UNKNOWN; T is TIMEOUT. Costs include unsuccessful requests.}',
              r'\label{tab:external}', r'\begin{tabular}{llrrrrrr}', r'\toprule',
              r'Cohort / method & Grade & N & P & U & ? & T & Mean s \\', r'\midrule']
    for cohort, title, arms in (
            ('MLP external', 'MLP', (('adaptive', 'ACT', 'HZ'), ('crown', 'CROWN path', 'CF'))),
            ('Conv V2', 'Conv', (('adaptive', 'Adaptive', 'HZ'), ('monolithic', 'Matched', 'HZ'), ('crown', 'CROWN path', 'CF')))):
        for arm, name, grade in arms:
            subset = [r for r in rows if r['cohort'] == cohort and r['arm'] == arm]
            n = sum(r['n'] for r in subset)
            counts = [sum(r[k] for r in subset) for k in ('positive', 'unsafe', 'unknown', 'timeout')]
            seconds = sum(r['mean_seconds'] * r['n'] for r in subset) / n
            cells = [title + ' / ' + name, grade, str(n), *(str(c) for c in counts), f'{seconds:.2f}']
            lines.append(' & '.join(cells) + r' \\')
    lines += [r'\bottomrule', r'\end{tabular}', r'\end{table}', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--write', action='store_true', help='create a NEW rendering; refuse overwrite')
    args = parser.parse_args()
    content = render()
    if args.check:
        if (ROOT / OUTPUT).read_text() != content:
            raise ValueError('review-paper table drift')
        print('PASS: review-paper tables reproduce the archived accounting')
    elif args.write:
        with (ROOT / OUTPUT).open('x') as stream:
            stream.write(content)
    else:
        print(content, end='')


if __name__ == '__main__':
    main()
